"""empty message

Revision ID: 85279ce0b1cf
Revises: 
Create Date: 2022-01-15 15:32:03.552877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85279ce0b1cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('rights_from', sa.DateTime(), nullable=True),
    sa.Column('rights_to', sa.DateTime(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rights')
    op.drop_table('documents')
    # ### end Alembic commands ###
